Repository db-ux-design-system/icon-font-tools, pull requests merged in 2024-11, with the labels that each got.

#309 docs: added a note for required attributes
  README.md
Labels: documentation, repo

#352 feat: add skip clean arg
  package.json
  src/clean-icons/index.ts
  src/generate-icon-fonts/data.ts
  src/generate-icon-fonts/index.ts
  src/types.ts
  tsconfig.json
Labels: repo

#353 fix: issue with truffle hog
  .github/workflows/00-scan-secrets.yml
Labels: cicd

#335 refactor: resolves a dependabot alert
  package-lock.json
  package.json
Labels: dependencies, repo
