Repository db-ux-design-system/icon-font-tools, pull requests merged in 2025-01, with the labels that each got.

#393 fix: issues with build
  package.json
  pnpm-lock.yaml
  src/commands/clean-icons/data.ts
  src/commands/clean-icons/index.ts
  src/commands/generate-icon-fonts/data.ts
  src/utils/index.ts
  src/utils/inquirer-process.ts
  src/utils/shared.ts
  tsconfig.json
Labels: repo

#394 chore: change package name from db-ui to db-ux
  README.md
  docs/API.md
  package.json
  src/data.ts
Labels: repo

#395 feat: add cosmiconfig to load config files
  README.md
  docs/API.md
  docs/CleanIcons.md
  docs/GenerateIconFonts.md
  package.json
  pnpm-lock.yaml
  src/api-docs.ts
  src/commands/clean-icons/data.ts
  src/commands/clean-icons/index.ts
  src/commands/generate-icon-fonts/data.ts
  src/commands/generate-icon-fonts/index.ts
  src/commands/generate-icon-fonts/utils/gather-icons.ts
  src/data.ts
  src/utils/config-process.ts
  src/utils/shared.ts
  test/generate-icon-fonts/config/brand.svg
  test/generate-icon-fonts/config/config.test.ts
  test/generate-icon-fonts/config/generate-icon-fonts.json
  test/generate-icon-fonts/config/ignore/brand.svg
Labels: repo

#396 Feat hygen
  docs/GenerateIconFonts.md
  hygen/README.md
  hygen/_templates/command/new/prompt.js
  hygen/_templates/command/new/src/commands/action.ejs.t
  hygen/_templates/command/new/src/commands/data.ejs.t
  hygen/_templates/command/new/src/commands/index.ejs.t
  hygen/_templates/command/new/src/programm-data/data-command.ejs.t
  hygen/_templates/command/new/src/programm-data/data-import.ejs.t
  hygen/_templates/command/new/src/programm-data/data-name-const.ejs.t
  hygen/_templates/command/new/src/test/package.json.ejs.t
  hygen/_templates/command/new/src/test/simple.ejs.t
  hygen/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/commands/clean-icons/action.ts
  src/commands/clean-icons/index.ts
  src/commands/generate-icon-fonts/action.ts
  src/commands/generate-icon-fonts/index.ts
  src/commands/generate-icon-fonts/utils/index.ts
  src/data.ts
  test/clean-icons/simple/simple.test.ts
  test/generate-icon-fonts/config/config.test.ts
  test/generate-icon-fonts/simple/simple.test.ts
Labels: repo

#397 Update README.md
  README.md
Labels: documentation, repo

#412 refactor: optimizations
  package-lock.json
  src/commands/clean-icons/data.ts
Labels: repo

#407 feat: icon subset
  .github/workflows/01-test.yml
  .gitignore
  README.md
  docs/API.md
  docs/IconSubset.md
  package.json
  pnpm-lock.yaml
  src/api-docs.ts
  src/commands/clean-icons/data.ts
  src/commands/generate-icon-fonts/data.ts
  src/commands/icon-subset/action.ts
  src/commands/icon-subset/data.ts
  src/commands/icon-subset/helpers/filter-icons.ts
  src/commands/icon-subset/helpers/ttx.ts
  src/commands/icon-subset/index.ts
  src/data.ts
  src/program.ts
  src/utils/shared.ts
  test/icon-subset/config/config.test.ts
  test/icon-subset/config/icon-subset.json
  test/icon-subset/simple/simple.test.ts
  test/icon-subset/test.woff2
  test/package.json
Labels: repo, cicd

#415 fix: build output as nodejs to allow using it inside `.js` file
  docs/API.md
  docs/GenerateIconFonts.md
  docs/IconSubset.md
  hygen/_templates/command/new/src/commands/command/action.ejs.t
  hygen/_templates/command/new/src/commands/command/data.ejs.t
  hygen/_templates/command/new/src/commands/command/index.ejs.t
  hygen/_templates/command/new/src/commands/index.ejs.t
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/api-docs.ts
  src/cli.ts
  src/commands/clean-icons/action.ts
  src/commands/clean-icons/data.ts
  src/commands/clean-icons/index.ts
  src/commands/generate-icon-fonts/action.ts
  src/commands/generate-icon-fonts/data.ts
  src/commands/generate-icon-fonts/index.ts
  src/commands/generate-icon-fonts/utils/gather-icons.ts
  src/commands/generate-icon-fonts/utils/svg-to-font.ts
  src/commands/icon-subset/action.ts
  src/commands/icon-subset/data.ts
  src/commands/icon-subset/helpers/filter-icons.ts
  src/commands/icon-subset/helpers/ttx.ts
  src/commands/icon-subset/index.ts
  src/commands/index.ts
  src/data.ts
  src/program.ts
  src/utils/inquirer-process.ts
  src/utils/shared.ts
  test/clean-icons/simple/simple.test.ts
  test/generate-icon-fonts/config/config.test.ts
  test/generate-icon-fonts/config/generate-icon-fonts.json
  test/generate-icon-fonts/simple/simple.test.ts
  test/icon-subset/config/config.test.ts
  test/icon-subset/config/icon-subset.json
  test/icon-subset/ignore-test.woff2
  test/icon-subset/simple/simple.test.ts
  test/package.json
  tsconfig.json
Labels: repo
